### PR TITLE
Added Events

### PR DESCRIPTION
**Pull request by RemainingToast**
Also SafeWalk was Added

### CODE REVIEW

**Comment by RemainingToast** [comment]
@IUDevman @yagel15637 @lukflug some review pls

**Comment by yagel15637** [comment]
compiling fails..? idk why but look into that:

```
  1 actionable task: 1 executed
            if (keyBinding.wasPressed()) MinecraftClient.getInstance().openScreen(clickGui);
                ^
  symbol:   variable keyBinding
  location: class Rhodium
```

**Comment by RemainingToast** [comment]
oh shit I didn't see this, yeah thats strange let me take a look

**Comment by IUDevman** [comment]
I'll merge this and work on the error with building, shouldn't be too hard to fix.

**Pull request merged**
